### ISSUE TITLE
Hello, I'm very interested in the work of C5, but I have a question regarding data collection. I'd like to know what kind of camera settings were used to capture these color-shifted images. When I take pictures with my EOS 600D, they appear as normal white, but due to lighting conditions, there is some color deviation. Can this also be considered as a color constancy task?

### ISSUE THREAD

**Issue by lf22222** [mahmoudnafifi/C5#12]

**Comment by mahmoudnafifi** [comment]
This work focuses on addressing the color cast present in raw images, which arises from the combination of the lighting conditions in the scene and the varying sensitivity of different color channels in the image, particularly the green channel. These color channel responses differ between cameras, making most learning-based color constancy methods specific to a particular camera sensor. In contrast, this work aims to overcome this limitation by utilizing additional images captured by the same camera to get some clues about the color channel biases of the camera being tested.

Based on your description, it appears that your images are in sRGB, not in raw format, and the color cast is a result of either errors in the camera's illumination estimation module or intentional deviations to match certain user preferences. If this is the case and you would like fix colors in sRGB, you may find this paper is useful:
https://github.com/mahmoudnafifi/WB_sRGB

**Comment by lf22222** [comment]
Ok, thank you very much. This article has been very useful to me.I'll keep an eye on your other work as well
